### ISSUE TITLE
Install command do nothing, need help ! 

### ISSUE THREAD

**Issue by Adrenogenesis** [ethicalhackingplayground/bxss#3]
I had installed  go version go1.15.3 linux/amd64, but `go get -u github.com/ethicalhackingplayground/bxss` do nothing.
How to install it please ?

**Comment by Mamilate** [comment]
go install github.com/ethicalhackingplayground/bxss@latest

**Comment by punam2104** [comment]
Same here .. I've tried both commands but not working..

**Comment by ethicalhackingplayground** [comment]
It should be all working fine now, just run the command:

```bash
go install -v github.com/ethicalhackingplayground/bxss/v2/cmd/bxss@latest
```

To install the tool, thanks a ton for all your support.
